// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UHSB_Bagalkot.Data.Models;

#nullable disable

namespace UHSB_Bagalkot.Data.Migrations
{
    [DbContext(typeof(Uhsb2025Context))]
    partial class Uhsb2025ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.FarmersProfile", b =>
                {
                    b.Property<int>("FarmerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FarmerId"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("LandSize")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Village")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FarmerId")
                        .HasName("PK__FarmersP__731B8888126DB797");

                    b.HasIndex(new[] { "Mobile" }, "UQ__FarmersP__6FAE0782B5B7AFAB")
                        .IsUnique();

                    b.ToTable("FarmersProfile", (string)null);
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.ItemContent", b =>
                {
                    b.Property<int>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContentId"));

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ContentId")
                        .HasName("PK__ItemCont__2907A81E44B946CF");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemContent", (string)null);
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__RefreshT__3214EC07EBAB120B");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.UhsbCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId")
                        .HasName("PK__UHSB_Cat__19093A0B6CC0EDA7");

                    b.ToTable("UHSB_Categories", (string)null);
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.UhsbCrop", b =>
                {
                    b.Property<int>("CropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CropId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CropId")
                        .HasName("PK__UHSB_Cro__9235611589353871");

                    b.HasIndex("CategoryId");

                    b.ToTable("UHSB_Crops", (string)null);
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.UhsbItemDeail", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SubSectionId")
                        .HasColumnType("int");

                    b.HasKey("ItemId")
                        .HasName("PK__UHSB_Ite__727E838BC58DFEC2");

                    b.HasIndex("SubSectionId");

                    b.ToTable("UHSB_ItemDeails", (string)null);
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.UhsbItemImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("ImageId")
                        .HasName("PK__UHSB_Ite__7516F70C28649EA1");

                    b.HasIndex("ItemId");

                    b.ToTable("UHSB_ItemImages", (string)null);
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.UhsbItemQnA", b =>
                {
                    b.Property<int>("QnAid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("QnAId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QnAid"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<byte?>("Datastatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("QnAid")
                        .HasName("PK__UHSB_Ite__C4DF8B097F677125");

                    b.HasIndex("ItemId");

                    b.ToTable("UHSB_ItemQnA", (string)null);
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.UhsbSection", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectionId"));

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SectionId")
                        .HasName("PK__UHSB_Sec__80EF087273D7BD88");

                    b.HasIndex("CropId");

                    b.ToTable("UHSB_Sections", (string)null);
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.UhsbSubSection", b =>
                {
                    b.Property<int>("SubSectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubSectionId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.HasKey("SubSectionId")
                        .HasName("PK__UHSB_Sub__A8281A1DB2865AD6");

                    b.HasIndex("SectionId");

                    b.ToTable("UHSB_SubSections", (string)null);
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.UhsbWeatherCastFileDetail", b =>
                {
                    b.Property<int>("WeatherFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeatherFileId"));

                    b.Property<DateOnly?>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("WeekEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("WeatherFileId");

                    b.ToTable("UHSB_WeatherCastFileDetails", (string)null);
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.UserMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("RoleType")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__UserMast__3214EC07A35B5BF1");

                    b.HasIndex(new[] { "PhoneNumber" }, "UQ__UserMast__85FB4E380FBF00DA")
                        .IsUnique();

                    b.ToTable("UserMaster", (string)null);
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__UserRole__3214EC079CB50282");

                    b.HasIndex(new[] { "RoleName" }, "UQ__UserRole__8A2B6160A53898F0")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.ItemContent", b =>
                {
                    b.HasOne("UHSB_Bagalkot.Data.Models.UhsbItemDeail", "Item")
                        .WithMany("ItemContents")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK_UHSB_ItemContent_UHSB_Items");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.RefreshToken", b =>
                {
                    b.HasOne("UHSB_Bagalkot.Data.Models.UserMaster", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_UserMaster");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.UhsbCrop", b =>
                {
                    b.HasOne("UHSB_Bagalkot.Data.Models.UhsbCategory", "Category")
                        .WithMany("UhsbCrops")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_UHSB_Crops_UHSB_Category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.UhsbItemDeail", b =>
                {
                    b.HasOne("UHSB_Bagalkot.Data.Models.UhsbSubSection", "SubSection")
                        .WithMany("UhsbItemDeails")
                        .HasForeignKey("SubSectionId")
                        .IsRequired()
                        .HasConstraintName("FK_UHSB_ItemDeails_UHSB_SubSection");

                    b.Navigation("SubSection");
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.UhsbItemImage", b =>
                {
                    b.HasOne("UHSB_Bagalkot.Data.Models.UhsbItemDeail", "Item")
                        .WithMany("UhsbItemImages")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK_UHSB_ItemImages_UHSB_Items");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.UhsbItemQnA", b =>
                {
                    b.HasOne("UHSB_Bagalkot.Data.Models.UhsbItemDeail", "Item")
                        .WithMany("UhsbItemQnAs")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK_UHSB_ItemQnA_UHSB_Items");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.UhsbSection", b =>
                {
                    b.HasOne("UHSB_Bagalkot.Data.Models.UhsbCrop", "Crop")
                        .WithMany("UhsbSections")
                        .HasForeignKey("CropId")
                        .IsRequired()
                        .HasConstraintName("FK_UHSB_Sections_UHSB_Crop");

                    b.Navigation("Crop");
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.UhsbSubSection", b =>
                {
                    b.HasOne("UHSB_Bagalkot.Data.Models.UhsbSection", "Section")
                        .WithMany("UhsbSubSections")
                        .HasForeignKey("SectionId")
                        .IsRequired()
                        .HasConstraintName("FK_UHSB_SubSections_UHSB_Section");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.UhsbCategory", b =>
                {
                    b.Navigation("UhsbCrops");
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.UhsbCrop", b =>
                {
                    b.Navigation("UhsbSections");
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.UhsbItemDeail", b =>
                {
                    b.Navigation("ItemContents");

                    b.Navigation("UhsbItemImages");

                    b.Navigation("UhsbItemQnAs");
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.UhsbSection", b =>
                {
                    b.Navigation("UhsbSubSections");
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.UhsbSubSection", b =>
                {
                    b.Navigation("UhsbItemDeails");
                });

            modelBuilder.Entity("UHSB_Bagalkot.Data.Models.UserMaster", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
